export type TrainedLangs = Record<string, string>
export const trainedLangsListEng: TrainedLangs = {
  "afr": "Afrikaans",
  "amh": "Amharic",
  "ara": "Arabic",
  "asm": "Assamese",
  "aze": "Azerbaijani",
  "aze_cyrl": "Azerbaijani - Cyrillic",
  "bel": "Belarusian",
  "ben": "Bengali",
  "bod": "Tibetan",
  "bos": "Bosnian",
  "bul": "Bulgarian",
  "cat": "Catalan; Valencian",
  "ceb": "Cebuano",
  "ces": "Czech",
  "chi_sim": "Chinese - Simplified",
  "chi_tra": "Chinese - Traditional",
  "chr": "Cherokee",
  "cym": "Welsh",
  "dan": "Danish",
  "deu": "German",
  "dzo": "Dzongkha",
  "ell": "Greek, Modern (1453-)",
  "eng": "English",
  "enm": "English, Middle (1100-1500)",
  "epo": "Esperanto",
  "est": "Estonian",
  "eus": "Basque",
  "fas": "Persian",
  "fin": "Finnish",
  "fra": "French",
  "frk": "German Fraktur",
  "frm": "French, Middle (ca. 1400-1600)",
  "gle": "Irish",
  "glg": "Galician",
  "grc": "Greek, Ancient (-1453)",
  "guj": "Gujarati",
  "hat": "Haitian; Haitian Creole",
  "heb": "Hebrew",
  "hin": "Hindi",
  "hrv": "Croatian",
  "hun": "Hungarian",
  "iku": "Inuktitut",
  "ind": "Indonesian",
  "isl": "Icelandic",
  "ita": "Italian",
  "ita_old": "Italian - Old",
  "jav": "Javanese",
  "jpn": "Japanese",
  "kan": "Kannada",
  "kat": "Georgian",
  "kat_old": "Georgian - Old",
  "kaz": "Kazakh",
  "khm": "Central Khmer",
  "kir": "Kirghiz; Kyrgyz",
  "kor": "Korean",
  "kur": "Kurdish",
  "lao": "Lao",
  "lat": "Latin",
  "lav": "Latvian",
  "lit": "Lithuanian",
  "mal": "Malayalam",
  "mar": "Marathi",
  "mkd": "Macedonian",
  "mlt": "Maltese",
  "msa": "Malay",
  "mya": "Burmese",
  "nep": "Nepali",
  "nld": "Dutch; Flemish",
  "nor": "Norwegian",
  "ori": "Oriya",
  "pan": "Panjabi; Punjabi",
  "pol": "Polish",
  "por": "Portuguese",
  "pus": "Pushto; Pashto",
  "ron": "Romanian; Moldavian; Moldovan",
  "rus": "Russian",
  "san": "Sanskrit",
  "sin": "Sinhala; Sinhalese",
  "slk": "Slovak",
  "slv": "Slovenian",
  "spa": "Spanish; Castilian",
  "spa_old": "Spanish; Castilian - Old",
  "sqi": "Albanian",
  "srp": "Serbian",
  "srp_latn": "Serbian - Latin",
  "swa": "Swahili",
  "swe": "Swedish",
  "syr": "Syriac",
  "tam": "Tamil",
  "tel": "Telugu",
  "tgk": "Tajik",
  "tgl": "Tagalog",
  "tha": "Thai",
  "tir": "Tigrinya",
  "tur": "Turkish",
  "uig": "Uighur; Uyghur",
  "ukr": "Ukrainian",
  "urd": "Urdu",
  "uzb": "Uzbek",
  "uzb_cyrl": "Uzbek - Cyrillic",
  "vie": "Vietnamese",
  "yid": "Yiddish"
}

export const trainedLangsListFr: TrainedLangs = {
  "afr": "Afrikaans",
  "amh": "Amharique",
  "ara": "Arabe",
  "asm": "Assamais",
  "aze": "Azerbaïdjanais",
  "aze_cyrl": "Azerbaïdjanais - Cyrillique",
  "bel": "Biélorusse",
  "ben": "Bengali",
  "bod": "Tibétain",
  "bos": "Bosniaque",
  "bul": "Bulgare",
  "cat": "Catalan; Valencien",
  "ceb": "Cebuano",
  "ces": "Tchèque",
  "chi_sim": "Chinois simplifié",
  "chi_tra": "Chinois traditionnel",
  "chr": "Cherokee",
  "cym": "Gallois",
  "dan": "Danois",
  "deu": "Allemand",
  "dzo": "Dzongkha",
  "ell": "Grec moderne (après 1453)",
  "eng": "Anglais",
  "enm": "Anglais moyen (1100-1500)",
  "epo": "Espéranto",
  "est": "Estonien",
  "eus": "Basque",
  "fas": "Persan",
  "fin": "Finnois",
  "fra": "Français",
  "frk": "Allemand Fraktur",
  "frm": "Français moyen (1400-1600)",
  "gle": "Irlandais",
  "glg": "Galicien",
  "grc": "Grec ancien (-1453)",
  "guj": "Gujarati",
  "hat": "Haïtien; Créole haïtien",
  "heb": "Hébreu",
  "hin": "Hindi",
  "hrv": "Croate",
  "hun": "Hongrois",
  "iku": "Inuktitut",
  "ind": "Indonésien",
  "isl": "Islandais",
  "ita": "Italien",
  "ita_old": "Italien ancien",
  "jav": "Javanais",
  "jpn": "Japonais",
  "kan": "Kannada",
  "kat": "Géorgien",
  "kat_old": "Géorgien ancien",
  "kaz": "Kazakh",
  "khm": "Khmer central",
  "kir": "Kirghize; Kirghiz",
  "kor": "Coréen",
  "kur": "Kurde",
  "lao": "Laotien",
  "lat": "Latin",
  "lav": "Letton",
  "lit": "Lituanien",
  "mal": "Malayalam",
  "mar": "Marathi",
  "mkd": "Macédonien",
  "mlt": "Maltais",
  "msa": "Malais",
  "mya": "Birman",
  "nep": "Népalais",
  "nld": "Néerlandais; Flamand",
  "nor": "Norvégien",
  "ori": "Oriya",
  "pan": "Pendjabi; Punjabi",
  "pol": "Polonais",
  "por": "Portugais",
  "pus": "Pachto",
  "ron": "Roumain; Moldave; Moldovan",
  "rus": "Russe",
  "san": "Sanskrit",
  "sin": "Cingalais; Cinghalais",
  "slk": "Slovaque",
  "slv": "Slovène",
  "spa": "Espagnol; Castillan",
  "spa_old": "Espagnol; Castillan - Ancien",
  "sqi": "Albanais",
  "srp": "Serbe",
  "srp_latn": "Serbe - Latin",
  "swa": "Swahili",
  "swe": "Suédois",
  "syr": "Syriaque",
  "tam": "Tamoul",
  "tel": "Télougou",
  "tgk": "Tadjik",
  "tgl": "Tagalog",
  "tha": "Thaï",
  "tir": "Tigrigna",
  "tur": "Turc",
  "uig": "Ouïghour",
  "ukr": "Ukrainien",
  "urd": "Ourdou",
  "uzb": "Ouzbek",
  "uzb_cyrl": "Ouzbek - Cyrillique",
  "vie": "Vietnamien",
  "yid": "Yiddish"
}

